version: '3'
services:
  jenkins:
    image: jenkinsci/blueocean
    user: root
    ports:
      - "8080:8080"
    volumes:
      - /docker/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock #dockerコンテナ内でdockerを実行するのに必要
    restart: always

