version: '3'
services:
  jenkins:
    build: .
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /docker/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock #dockerコンテナ内でdockerを実行するのに必要
    restart: always

